"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE AddDiscountToProduct  "
"	-- Add the parameters for the stored procedure here "
"	@ProductId INT, "
"	@DiscountId INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	Insert INTO Products_Discount(ProductId,DiscountId) "
"	Values (@ProductId, @DiscountId) "
"END "
