"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE [dbo].[GetProductsByDiscountId] "
"	-- Add the parameters for the stored procedure here "
"	@DiscountId INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	SELECT pd.*,p.Name,p.Price,p.CategoryID "
"	FROM Products_Discount pd "
"	INNER JOIN Products p ON pd.ProductId = p.Id "
"	WHERE pd.DiscountId = @DiscountId "
"END "
