"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE GetProductsByDiscountId "
"	-- Add the parameters for the stored procedure here "
"	@DiscountId INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	SELECT * "
"	FROM "
"	Products_Discount "
"	Where Products_Discount.DiscountId=@DiscountId "
"END "
