"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE InsertDiscount "
"	-- Add the parameters for the stored procedure here "
"	@Percentage float, "
"	@StartDate datetime, "
"	@EndDate datetime "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	Insert INTO Discounts(Percentage,StartDate,EndDate) "
"	Values(@Percentage,@StartDate,@EndDate) "
"END "
