"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE InsertProduct  "
"	-- Add the parameters for the stored procedure here "
"	@Name nvarchar(100), "
"	@Price float, "
"	@CategoryID INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	INSERT INTO Products(Name,Price,CategoryID) "
"	VALUES (@Name,@Price,@CategoryID) "
"END "
