"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE UpdateDiscount  "
"	-- Add the parameters for the stored procedure here "
"	@Id INT, "
"	@Percentage float, "
"	@StartDate datetime, "
"	@EndDate datetime "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	Update Discounts "
"	SET Percentage = @Percentage,StartDate=@StartDate,EndDate= @EndDate "
"	WHERE Id = @Id "
"END "
