"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE UpdateProductDiscount "
"	-- Add the parameters for the stored procedure here "
"	@Id INT, "
"	@ProductId INT, "
"	@DiscountId INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	Update Products_Discount "
"	Set ProductId=@ProductId,DiscountId=@DiscountId "
"	WHERE Id =@Id "
"END "
