"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE UpdateProduct  "
"	-- Add the parameters for the stored procedure here "
"	@Id INT, "
"	@Name nvarchar(100), "
"	@Price float, "
"	@CategoryID INT "
"AS "
"BEGIN "
"	-- SET NOCOUNT ON added to prevent extra result sets from "
"	-- interfering with SELECT statements. "
"	SET NOCOUNT ON; "
" "
"    -- Insert statements for procedure here "
"	Update Products "
"	SET Name = @Name,Price = @Price,CategoryID=@CategoryID "
"	Where Id =@Id "
"END "
