"-- ============================================= "
"-- Author:		<Author,,Name> "
"-- Create date: <Create Date,,> "
"-- Description:	<Description,,> "
"-- ============================================= "
"CREATE PROCEDURE [dbo].[usp_CheckProductDiscountExistence] "
"    @ProductId INT, "
"    @DiscountId INT, "
"    @Exists BIT OUTPUT "
"AS "
"BEGIN "
"    SET NOCOUNT ON; "
" "
"    IF EXISTS (SELECT 1 FROM Products_Discount WHERE ProductId = @ProductId AND DiscountId = @DiscountId) "
"        SET @Exists = 1; "
"    ELSE "
"        SET @Exists = 0; "
"END "
